name: Deployment

on:
  push:
    branches:
      - master
jobs:
  deployment:
    runs-on: ubuntu-latest
#    environment: production
#    concurrency: production
    steps:
    - name: install ssh keys
      # check this thread to understand why its needed:
      # https://stackoverflow.com/a/70447517
      run: |
        install -m 600 -D /dev/null ~/.ssh/id_rsa
        echo "${{ secrets.SSH_PRIVATE_KEY_OWN_SERVER }}" > ~/.ssh/id_rsa
        ssh-keyscan -H ${{ secrets.SSH_HOST_OWN_SERVER }} > ~/.ssh/known_hosts
    - name: connect and pull
      run: ssh ${{ secrets.SSH_USER_OWN_SERVER }}@${{ secrets.SSH_HOST_OWN_SERVER }} "cd ${{ secrets.WORK_DIR_GROUP_UAHBOT }} && git checkout ${{ secrets.BRANCH_UAHBOT }} && git pull  && exit"
    - name: cleanup
      run: rm -rf ~/.ssh







#      On the GitHub website:
#&& sudo systemctl  restart bot.service
#        Go to “Settings > Secrets > Actions”
#        Create the following secrets:
#          SSH_PRIVATE_KEY_OWN_SERVER: content of the private key file
#          SSH_HOST_OWN_SERVER: hostname/ip-address of your server
#          WORK_DIR_GROUP_UAHBOT:  path to uah repo
#          BRANCH_UAHBOT: name of the main branch
#          SSH_USER_OWN_SERVER
#        Go to the “Actions” tab in your GitHub repository

